### ISSUE TITLE
Issue running tests on both CPU and GPU based systems

### ISSUE THREAD

**Issue by johnmauff** [mmbell/samurai#11]
The current build system creates executables with the name samurai regardless of whether it is for the CPU or GPU base system.  Unfortunately, this prevents tests from being run on both the CPU and GPU simultaneously.  While not a big issue now, it may cause problems with the addition of a CI/CD framework.

**Comment by sjsprecious** [comment]
Thanks @johnmauff for pointing out this drawback. I think a bigger problem here is that if we build/run a CPU and GPU case at the same time, they are modifying the same `CMakeLists.txt` file and this will cause a confliction. 

The CI workflow on GitHub uses container and each container should have its own space. Thus as long as we put CPU and GPU tests into different containers, it should be fine.

**Comment by johnmauff** [comment]
I believe that this issue as been addressed by a recent commit from Mike Dixon.
