### ISSUE TITLE
Changing the default branch in git

### ISSUE THREAD

**Issue by johnmauff** [mmbell/samurai#17]
@mmbell Would it be possible to rename the default branch to be main versus the current name of master.  This can be done by following the following instructions:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by mmbell** [comment]
I am fine with that suggestion. When I first started this repository the convention was to use "master" but that evidently convention has changed over time. I would be OK with changing it to "main".

**Comment by sjsprecious** [comment]
Hi @mmbell , also could you protect the "main" branch by following the instructions at https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule? In this way, we could prevent anyone from directly committing changes to the "main" branch in the future.

**Comment by mmbell** [comment]
@mike-dixon I'm wondering whether this change will affect your lrose-core builds if they explicitly rely on the 'master' branch designation. I am inclined to make this change prior to finalizing the 'Colette' release so that 'main' is the standard moving forward, but want to make you aware of the change and check for any unintended effects on the core. Please advise, thanks.

**Comment by mmbell** [comment]
A new branch named "main" was created off the current "master" and set as the default. Branch protection was added to "main" to enforce pull requests with at least 1 code reviewer for all merges. If there are any other recommended changes to the rules please let me know. I will leave the "master" branch intact temporarily to prevent unintended breakage, but will delete in the near future as it will soon become deprecated. Once everything has been verified and we are happy with the ruleset then we can close this issue.
