### ISSUE TITLE
Add the CodeCoverage to the CI workflow

### ISSUE THREAD

**Issue by sjsprecious** [mmbell/samurai#53]
According to the discussion with John and Sheri, it will be great to report how much percent of SAMURAI C++ code is touched during a CI test.

This can be done by incorporating the `CodeCov` application (https://docs.codecov.com/docs/quick-start) into the existing CI workflow.

**Comment by cenamiller** [comment]
At this stage, Jian has tested the code and needs Michael's help to set up account information for  SAMURAI PR
