### ISSUE TITLE
Bug in Casper_a100_submit.sh

### ISSUE THREAD

**Issue by markonders** [mmbell/samurai#55]
Error in Running Casper a100 script. 

Error Message :

GPU run; using 1 thread and 1 GPU
./ncar_run.sh: line 38: 207981 Illegal instruction     (core dumped) ${EXE} -params $*

Tried Interactive Session and were able to confirm these parameters were available to use. Used this command:
execcasper -l walltime=00:30:00 -l gpu_type=a100 -l select=1:ncpus=36:ompthreads=1:mem=700GB:ngpus=1 -A NEOL0013

Can confirm run folder is created, but there is no run/timing or run/samurai logs because the program is not running.

**Comment by sjsprecious** [comment]
Interesting. I ran the command manually in an interactive session and it worked fine. But if I tried the PBS submission script, it failed with the same error reported here.

**Comment by cenamiller** [comment]
John and Jian can run on Casper V100 and Derecho A100, still having issues with Casper A100. Suspect system issue, Jian reported to CSG

**Comment by sjsprecious** [comment]
I just checked out Mark's fork (https://github.com/markonders/samurai/tree/main, commit: `7d4a308`) and was able to run the Beltrami test on Casper's A100 now. Thanks @markonders for fixing this issue.
