### ISSUE TITLE
Beltrami Validation Reference file

### ISSUE THREAD

**Issue by cenamiller** [mmbell/samurai#56]

**Comment by johnmauff** [comment]
Addressed by PR #95

**Comment by cenamiller** [comment]
Here is what I think might work well for the Beltrami test reference sounding file.  It is very simple, but I am hopeful that if we prescribe a simple reference sounding as described then the results will converge more quickly. We would need to use this sounding instead  "input_sounding_dunion_MT.txt" for both the SAMURAI wind retrieval and the thermodynamic retrieval. I believe that the 'balanced' scripts calculate things with respect to the reference sounding, so maybe that makes those simpler too.<br><br>The second problem is what the analytic pressure gradient should be for verification. That is the derivation I started but didn't make it too far yet. The pressure gradient term in the current framework is a little different than what is in the literature, but I think with this sounding it is simpler. I'll keep working on the derivation for verification, but hopefully this all makes sense and gives some direction on this. If you are interested in the details of the sounding please read on, but they are not necessary for using it for practical application. Feel free to stop reading here! Thanks!<br><br>The sounding we want is a constant theta_rho with height, such that theta_rho_bar is the same everywhere to simplify the problem. Density and pressure still decrease with height, but do so at exactly the same rate as the temperature so that theta stays constant. Since theta_rho is just theta with the effects of moisture, I just set the mixing ratio to zero to make the problem dry.  With those assumptions, the reference state file (attached) is very simple. It sets the surface pressure to 1000 hPa, surface potential temperature to 300 K, and has no moisture or background wind. The potential temperature is constant through all the levels up to the top of the domain. In theory this should work! We would need to test it but I don't have the latest version of the code on my laptop.<br><br> Normally the pressure gradient term is written as<br><br>(1/rho)dp/dx<br><br>which is the form in the Shapiro papers, but it can also be written as:<br><br>(c_p * theta_rho_bar) * d(pi')/dx<br><br>which is the form used in the A - E equations in SAMURAI-TR. Using this sounding, the first term in parentheses is constant so it simplifies the problem. The pi_bar term is also constant at each vertical level in the sounding, so that d(pi_bar)/dx = 0 and that term drops out. The analytic pressure gradient is then just the perturbation part, which is a first order differential equation that is integrable. Sorry for all the math :)<br><br>Best,<br>Michael</div></div></div></div></div>

**Comment by cenamiller** [comment]
https://drive.google.com/drive/folders/1xFdZMF6CXzSTaUu0PvJ7fEz9kmHDp1nC
