### ISSUE TITLE
Add the modified input NetCDF subroutines to support reading of Samurai wind output

### ISSUE THREAD

**Issue by johnmauff** [mmbell/samurai#75]

**Comment by cenamiller** [comment]
Brian's commit on removing QT calls https://github.com/mmbell/samurai/commit/5ec4558080c645aabe98da679c80bc3276a5c193

**Comment by cenamiller** [comment]
https://github.com/cenamiller/samurai/tree/issue75

**Comment by cenamiller** [comment]
implement calcA-E in VarDriver.cpp, similar to bool VarDriver3D::preProcessMetObs()

**Comment by johnmauff** [comment]
@cenamiller. I was just looking at some of the code that you added for the readNetCDF_thermo() function.  It appears that you decided not to add this as a class.  So it is missing construct and destructor functions necessary to reproduce the loadObservations() method that includes the allocation and deallocation of a number of variables.  Could you clarify how to work around this missing functionality.

**Comment by cenamiller** [comment]
Hi @johnmauff  -   I added the allocation/deallocation of the thermo variables needed by the thermo_reference/NetCDF_XYZ class to an if-condition in the samurai_wind/VarDriver constructor and destructor that I thought could check the mode. Does that give you what you need for loadObservations()?

**Comment by cenamiller** [comment]
The logic was that it was in the style of the samurai_wind code to have the various readers handled by VarDriver

**Comment by cenamiller** [comment]
Ahhh - I see what you're talking about now for loadObservations. Let's check how it's handled in samurai_wind because I don't think that class exists

**Comment by johnmauff** [comment]
No, it does not exist in the Samurai Wind code.  I think it would be best if the NetCDF_XYZ class from Samurai THERMO is just directly added.  We can certainly cleanup the duplicate code in the future.

**Comment by cenamiller** [comment]
Sounds good! And for our future reference during cleanup I think we can move it to VarDriver and use read_classnc() as a template

**Comment by cenamiller** [comment]
In the process of adding the thermo NetCDF class without ~QTStrings~

**Comment by cenamiller** [comment]
#100 Okay, here's the NetCDF_XYZ class to try @johnmauff
