### ISSUE TITLE
Modify the output NetCDF subrouties to generate Thermo output

### ISSUE THREAD

**Issue by johnmauff** [mmbell/samurai#76]
Several different output routines (outputAnalysis) exist in Samuari that write NetCDF files.  These output routines are specific for each different type of coordinate system 'XYZ, RTZ' and are located in CostFunctionXYZ.cpp for the wind version of Samurai and 'thermo_reference/CostFunctionThermoXYZ.cpp' for the thermo version of Samurai.  The Thermo version of outputAnalysis needs to be added to the common code base.  For now, I recommend that a nearly duplicate method outputAnalysisTR is created.  The elimination of duplicate code can performed on a separate PR.

**Comment by cenamiller** [comment]
See how output should be renamed: #78

**Comment by cenamiller** [comment]
John will describe how subroutines need to be changed

**Comment by cenamiller** [comment]
developed at /glade/derecho/scratch/cmille73/APAR/issue76_NC_TRoutput

Still need to do #78 and test

**Comment by cenamiller** [comment]
Kamino cloned this issue to [NCAR/samurai-dev](https://github.com/NCAR/samurai-dev/issues/3)
