### ISSUE TITLE
Cleanup magic 7's and other dimension issues.

### ISSUE THREAD

**Issue by cenamiller** [mmbell/samurai#87]
There are a lot of '7's floating around the code. Sometimes refer to 
1. number of variables
2. size of meta data
3. indexing

Need to consolidate to global variables for 1 and 2 points

May require a little extra work to get these variables accessible throughout code?

**Comment by cenamiller** [comment]
This is a top priority because it's required for the control code to work for the 'thermo' mode

**Comment by cenamiller** [comment]
John will do a commit where the variables currently need to be set in 2 locations - Supreeth is going to try to get that down to one global location. These values should be set in the parameter file, instead of being hard coded. 

Our goal is to not need to recompile between wind and thermo runs - there should be one executable that takes the mode as a parameter

**Comment by cenamiller** [comment]
John will create a feature branch with his code progress. @johnmauff

**Comment by johnmauff** [comment]
PR #94 was created that partially addresses this issue

**Comment by cenamiller** [comment]
Closed with PR #94
